### PR TITLE
Matrix question type

### PR DESCRIPTION
**Pull request by arulmabr**
Adding QuestionMatrix, please do check and let me know if everything is optimized and documented. 

Works fine in my local environment and you can use this for quick testing: https://gist.github.com/arulmabr/59f525b724763f44bcc7fd0562b1b40b

### CODE REVIEW

**Comment by johnjosephhorton** [comment]
Awesome - check this out @rbyh !

re: the failing test - I think it's just that the validator now raises a more specific exception: 
```python
        with pytest.raises(ValueError, match="question_name cannot be empty"):
>           QuestionMatrix(
                question_name="",
                **{k: v for k, v in valid_question.items() if k != "question_name"}
            )
```

**Comment by johnjosephhorton** [comment]
@arulmabr if you want to run the tests locally, it's 
```
make tests
make tests-doctests
```
They're documented / defined in the Makefile

**Comment by arulmabr** [comment]
Noted, thanks.

**Comment by johnjosephhorton** [comment]
@arulmabr & @rbyh Here's a good example of a matrix question in the wild, ironically, about AI: 
Screenshot 2024-12-03 at 10 20 49 AM

**Comment by arulmabr** [comment]
@johnjosephhorton 
image

**Review by johnjosephhorton — APPROVED** [review]

**Comment by johnjosephhorton** [comment]
Awesome work @arulmabr !

**Pull request merged**
