### PR TITLE
Auth flow, model endpoint, and results visibility

### PR DESCRIPTION
**Pull request by onmyraedar**
- Users can now log in with an EDSL auth token to retrieve their API key and write it to .env
- `Model.available()` now uses the pricing JSON from Coop as a fallback to identify available models
- `Jobs.run()` now has an optional parameter, `remote_inference_results_visibility`, that determines the initial visibility of the Results object from remote inference

### CODE REVIEW

**Review by apostolosfilippas — APPROVED** [review]

**Comment by rbyh** [comment]
@onmyraedar Am I not using this parameter correctly? Thanks!
image

**Comment by onmyraedar** [comment]
Hi! You're using it correctly. Which EDSL version are you on?

**Comment by rbyh** [comment]
I am updating and pulling from main but still showing  0.1.37.dev1

**Comment by rbyh** [comment]
I'm going to reinstall, something not right.

**Comment by rbyh** [comment]
@onmyraedar all set now, these work fine for me, thx!

**Comment by onmyraedar** [comment]
Thanks for letting me know!

**Pull request merged**
