### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by johnjosephhorton**

### CODE REVIEW

**Review by johnjosephhorton — COMMENTED** [review]
@zer0dss This should help make the Model.available faster. Can you take a look?
1. Uses threads for the service calls 
2. Breaks up the logic into a few helper classes 
3. Make the sequence in which we get models configurable (local, coop, cache)

**Comment by zer0dss** [comment]
@johnjosephhorton I will chick it in ~1 hour.

**Comment by zer0dss** [comment]
@johnjosephhorton, I've checked the changes. The new solution is much faster and fixes issue #1308.
One question: What is the idea behind fetching available services from cache?

**Comment by johnjosephhorton** [comment]
@apostolosfilippas I think this can be approved

**Review by apostolosfilippas — APPROVED** [review]

**Pull request merged**
