### PR TITLE
Deal with missing payload in coop interaction

### PR DESCRIPTION
**Pull request by johnjosephhorton**
On a coop pull request, the payload can be 'None'

### CODE REVIEW

**Comment by johnjosephhorton** [comment]
Doctests are failing because this is showing up in even in examples not using an API. Can't find this message in our code so not sure source:
```
{"detail":"The API key you provided is invalid."}
```
@zer0dss can you try to reproduce and potentially repair?

**Comment by zer0dss** [comment]
I am testing now.

**Comment by zer0dss** [comment]
I don't get the issue on local when I run the tests

**Comment by johnjosephhorton** [comment]
yeah, I didn't get it locally either - happened on github actions only

**Comment by apostolosfilippas** [comment]
this issue came from the fact that there was a print statement added to coop, and Results.example() calls coop.edsl_settings

**Review by apostolosfilippas — APPROVED** [review]

**Pull request merged**
